# Generated by Django 3.1.4 on 2021-05-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210420_1823'),
        ('emails', '0002_auto_20210503_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEmailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, max_length=100)),
                ('email_host_user', models.EmailField(blank=True, max_length=100)),
                ('email_host_password', models.CharField(blank=True, max_length=50)),
                ('port', models.IntegerField(blank=True)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
        ),
    ]
