# Generated by Django 3.1.4 on 2021-05-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_businessemailsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessemailsetting',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
