# Generated by Django 3.1.4 on 2021-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20210506_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessemailsetting',
            name='email_use_tls',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='False', max_length=10),
        ),
    ]
