# Generated by Django 3.1.4 on 2021-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20210506_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessemailsetting',
            name='email_use_tls',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='True', max_length=10),
        ),
    ]
