# Generated by Django 3.1.4 on 2021-05-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_auto_20210509_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='to_address',
            new_name='recipients',
        ),
    ]
