# Generated by Django 3.1.4 on 2021-07-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_auto_20210509_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessemailsetting',
            name='is_settings_verified',
            field=models.BooleanField(default=False),
        ),
    ]
