# Generated by Django 3.1.4 on 2021-11-14 20:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_businessemailsetting_is_settings_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_body_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='email_body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='email_body_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='subject_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='subject_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='subject_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
