# Generated by Django 3.1.4 on 2021-01-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210101_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitecontact',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitecontact',
            name='otp',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='sitecontact',
            name='resend_counter',
            field=models.IntegerField(default=0),
        ),
    ]
