# Generated by Django 3.1.4 on 2021-01-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20210101_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='is_otp_expired',
            field=models.BooleanField(default=False),
        ),
    ]
