# Generated by Django 3.1.4 on 2021-01-03 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_sitecontact_is_otp_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='otp_updated_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
