# Generated by Django 3.1.4 on 2021-01-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_sitecontact_otp_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontact',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='otp_updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
