# Generated by Django 3.1.4 on 2021-01-04 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20210104_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontact',
            name='otp_updated_time',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
