# Generated by Django 3.1.4 on 2021-07-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210104_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontact',
            name='is_otp_expired',
        ),
        migrations.RemoveField(
            model_name='sitecontact',
            name='is_otp_sent',
        ),
        migrations.RemoveField(
            model_name='sitecontact',
            name='is_otp_verified',
        ),
        migrations.RemoveField(
            model_name='sitecontact',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='sitecontact',
            name='otp_resend_counter',
        ),
        migrations.RemoveField(
            model_name='sitecontact',
            name='otp_updated_time',
        ),
    ]
