# Generated by Django 3.1.4 on 2021-09-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20210719_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontact',
            name='subject',
            field=models.CharField(max_length=250),
        ),
    ]
