# Generated by Django 3.1.4 on 2021-10-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20210921_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontact',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
