# Generated by Django 3.1.4 on 2021-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_decription',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='PlanFeature',
        ),
    ]
