# Generated by Django 3.1.4 on 2021-04-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_plan_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_active',
        ),
    ]
