# Generated by Django 3.1.4 on 2021-04-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_plan_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_decription',
            new_name='plan_description',
        ),
    ]
