# Generated by Django 3.1.4 on 2021-04-16 22:28

from django.db import migrations, models
import django.db.models.deletion
import plans.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_taxonplan_is_active'),
        ('plans', '0005_auto_20210417_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='PlanOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('tax', models.FloatField()),
                ('tax_data', models.JSONField(default=plans.models.tax_data_default, help_text="Data format: {'tax_type':{'tax_value':'tax_amount'}}")),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
                ('plan_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.planpayment')),
            ],
        ),
    ]
