# Generated by Django 3.1.4 on 2021-04-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_planorder_planpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='planorder',
            name='order_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
