# Generated by Django 3.1.4 on 2021-11-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_planorder_account_manager_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_description_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_description_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_description_fr',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
