# Generated by Django 3.1.4 on 2021-04-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210219_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='tax_percentage',
        ),
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(max_length=20)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.tax')),
            ],
        ),
    ]
