# Generated by Django 3.1.4 on 2021-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210415_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxsetting',
            name='tax_value',
            field=models.FloatField(),
        ),
    ]
