# Generated by Django 3.1.4 on 2021-04-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20210416_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxsetting',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
