# Generated by Django 3.1.4 on 2021-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20210416_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsetting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
