# Generated by Django 3.1.4 on 2021-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_taxsetting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxsetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
