# Generated by Django 3.1.4 on 2021-07-22 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20210416_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcart',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
