# Generated by Django 3.1.4 on 2021-07-17 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdata',
            name='is_active',
        ),
    ]
