# Generated by Django 3.1.4 on 2021-05-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='business',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
