# Generated by Django 3.1.4 on 2021-03-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='banner',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BannerImage',
        ),
    ]
