# Generated by Django 3.1.4 on 2021-04-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210420_1823'),
        ('sitesettings', '0002_auto_20210304_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(blank=True, upload_to='banner_images')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=500, null=True)),
                ('button_name', models.CharField(blank=True, max_length=20, null=True)),
                ('button_color', models.CharField(blank=True, max_length=20, null=True)),
                ('content_align', models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='center', max_length=10)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesettings.banner')),
            ],
        ),
    ]
