# Generated by Django 3.1.4 on 2021-04-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210420_1823'),
        ('sitesettings', '0003_banner_bannerimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Homepage',
        ),
        migrations.RenameField(
            model_name='bannerimage',
            old_name='banner',
            new_name='homepage',
        ),
    ]
