# Generated by Django 3.1.4 on 2021-04-20 21:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0004_auto_20210421_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to='store_feature_icons')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=30, null=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesettings.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='ParallaxBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallax_image', models.ImageField(blank=True, upload_to='parallax_image')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('button_name', models.CharField(blank=True, max_length=20, null=True)),
                ('button_color', models.CharField(blank=True, max_length=20, null=True)),
                ('content_align', models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='center', max_length=10)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesettings.homepage')),
            ],
        ),
    ]
