# Generated by Django 3.1.4 on 2021-04-27 09:35

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0005_parallaxbackground_storefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='content_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
    ]
