# Generated by Django 3.1.4 on 2021-04-27 09:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0006_auto_20210427_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='color',
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='button_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
