# Generated by Django 3.1.4 on 2021-04-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0008_bannerimage_button_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='button_link',
            field=models.URLField(default='#', max_length=255, null=True),
        ),
    ]
