# Generated by Django 3.1.4 on 2021-05-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0012_auto_20210427_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallaxbackground',
            name='button_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
