# Generated by Django 3.1.4 on 2021-05-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0014_auto_20210510_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='pin_code',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
