# Generated by Django 3.1.4 on 2021-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0015_contactpage_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
