# Generated by Django 3.1.4 on 2021-05-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0016_auto_20210510_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_credit',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
