# Generated by Django 3.1.4 on 2021-05-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0020_auto_20210514_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='image',
            new_name='cover_image',
        ),
    ]
