# Generated by Django 3.1.4 on 2021-06-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0022_policy_termsandcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='storefeature',
            name='feature_url',
            field=models.URLField(blank=True),
        ),
    ]
