# Generated by Django 3.1.4 on 2021-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0023_storefeature_feature_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='footer_credit',
            new_name='footer_credit1',
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_credit2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_url',
            field=models.URLField(blank=True),
        ),
    ]
