# Generated by Django 3.1.4 on 2021-06-09 09:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0025_footer_footer_credit3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='footer_credit1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_credit2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_credit3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_url',
        ),
        migrations.AddField(
            model_name='footer',
            name='footer_text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
