# Generated by Django 3.1.4 on 2021-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0027_topbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
