# Generated by Django 3.1.4 on 2021-06-15 15:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0028_topbar_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='about')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('header_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesettings.aboutpage')),
            ],
        ),
    ]
