# Generated by Django 3.1.4 on 2021-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0028_topbar_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_align',
            field=models.CharField(choices=[('left', 'LEFT'), ('center', 'CENTER'), ('right', 'RIGHT')], default='center', max_length=10),
        ),
    ]
