# Generated by Django 3.1.4 on 2021-06-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0029_auto_20210615_2058'),
        ('sitesettings', '0029_footer_footer_align'),
    ]

    operations = [
    ]
