# Generated by Django 3.1.4 on 2021-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0030_merge_20210619_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
    ]
