# Generated by Django 3.1.4 on 2021-09-13 20:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0041_cashondelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='brief',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='service_details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
