# Generated by Django 3.1.4 on 2021-09-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0044_frontpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
