# Generated by Django 3.1.4 on 2021-09-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0045_frontpage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpage',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='frontpages'),
        ),
    ]
