# Generated by Django 3.1.4 on 2021-09-27 10:46

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0046_auto_20210927_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='banner_images')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_title', models.TextField(blank=True, max_length=500, null=True)),
                ('button_name', models.CharField(blank=True, max_length=20, null=True)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('button_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('content_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesettings.homepage')),
            ],
        ),
    ]
