# Generated by Django 3.1.4 on 2021-09-27 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0048_auto_20210927_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobanner',
            name='video',
            field=models.FileField(blank=True, upload_to='banner_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avi', 'mp4', 'mkv'])]),
        ),
    ]
