# Generated by Django 3.1.4 on 2021-09-27 11:44

from django.db import migrations, models
import sitesettings.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0049_auto_20210927_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobanner',
            name='video',
            field=models.FileField(blank=True, upload_to='banner_images', validators=[sitesettings.validators.validate_video_file_extension]),
        ),
    ]
