# Generated by Django 3.1.4 on 2021-09-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0050_auto_20210927_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallaxbackground',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
