# Generated by Django 3.1.4 on 2021-09-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0051_auto_20210929_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontpage',
            name='preview_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
