# Generated by Django 3.1.4 on 2021-09-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0052_auto_20210929_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='site_logo_light',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
    ]
