# Generated by Django 3.1.4 on 2021-10-17 19:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0054_languageactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='sub_title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
