# Generated by Django 3.1.4 on 2021-11-08 16:53

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_dashboardimage'),
        ('sitesettings', '0056_auto_20211020_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageCTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_title', models.TextField(blank=True, max_length=255, null=True)),
                ('button_name', models.CharField(blank=True, max_length=20, null=True)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('button_text_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('button_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('content_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
        ),
    ]
