# Generated by Django 3.1.4 on 2021-11-13 19:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0057_servicepagecta'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='topbar_text_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='topbar_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topbar',
            name='topbar_text_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
