# Generated by Django 3.1.4 on 2021-06-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_comment_is_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
    ]
