# Generated by Django 3.1.4 on 2021-11-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20211112_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category_fr',
        ),
    ]
