# Generated by Django 3.1.4 on 2021-01-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalmanager',
            name='is_account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regionalmanager',
            name='is_verification_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
