# Generated by Django 3.1.4 on 2021-01-07 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210106_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalmanager',
            name='account_expiry_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
