# Generated by Django 3.1.4 on 2021-01-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_regionalmanager_account_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalmanager',
            name='account_expiry_date',
            field=models.DateField(),
        ),
    ]
