# Generated by Django 3.1.4 on 2021-01-09 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210108_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='is_account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_verification_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
