# Generated by Django 3.1.4 on 2021-02-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210220_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalmanager',
            name='is_editing',
            field=models.BooleanField(default=False),
        ),
    ]
