# Generated by Django 3.1.4 on 2021-02-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_regionalmanager_is_editing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalmanager',
            name='is_editing',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
