# Generated by Django 3.1.4 on 2021-02-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210224_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_editing',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='regionalmanager',
            name='is_account_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='regionalmanager',
            name='is_editing',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='regionalmanager',
            name='is_verification_email_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_business',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_regional_manager',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
