# Generated by Django 3.1.4 on 2021-04-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_remove_plan_is_active'),
        ('accounts', '0012_business_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
    ]
