# Generated by Django 3.1.4 on 2021-04-16 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_taxonplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonplan',
            name='is_active',
        ),
    ]
