# Generated by Django 3.1.4 on 2021-04-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_taxonplan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_regional_manager',
            field=models.BooleanField(default=False),
        ),
    ]
