# Generated by Django 3.1.4 on 2021-07-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210508_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_landing_image', models.ImageField(blank=True, default='default/dashboard-landing-image.png', upload_to='accounts/%Y/%m/%d')),
                ('account_manager_landing_image', models.ImageField(blank=True, default='default/dashboard-landing-image.png', upload_to='accounts/%Y/%m/%d')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
        ),
    ]
