# Generated by Django 3.1.4 on 2021-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_dashboardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address_line_1_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='address_line_1_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='address_line_1_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='address_line_2_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='address_line_2_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='address_line_2_fr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='city_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='city_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='city_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='company_name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='company_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='company_name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
