# Generated by Django 3.1.4 on 2021-06-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210604_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='account_expiry_date',
            field=models.DateField(),
        ),
    ]
