# Generated by Django 3.1.4 on 2021-06-04 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_planorder_account_manager_commission'),
        ('accounts', '0021_auto_20210604_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
    ]
