# Generated by Django 3.1.4 on 2021-02-26 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_auto_20210226_1420'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0002_auto_20210120_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('PayPal', 'PayPal'), ('Bank Account', 'Bank Account')], max_length=50)),
                ('paypal_address', models.EmailField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=50)),
                ('bank_code', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
