# Generated by Django 3.1.4 on 2021-04-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_paymentsetting_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsetting',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PayPal', 'PayPal'), ('Bank Account', 'Bank Account')], max_length=50),
        ),
    ]
