# Generated by Django 3.1.4 on 2021-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210219_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(default='test', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(default='test', editable=False, max_length=50),
        ),
    ]
