# Generated by Django 3.1.4 on 2021-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210220_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='tax',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
