# Generated by Django 3.1.4 on 2021-02-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210220_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='tax',
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=1.5),
        ),
    ]
