# Generated by Django 3.1.4 on 2021-02-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_orderproduct_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin_code',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
