# Generated by Django 3.1.4 on 2021-02-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin_code',
            field=models.CharField(max_length=10),
        ),
    ]
