# Generated by Django 3.1.4 on 2021-04-15 20:21

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210304_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(default=orders.models.tax_data_default),
        ),
    ]
