# Generated by Django 3.1.4 on 2021-04-15 22:04

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_tax_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(default=orders.models.tax_data_default, help_text="Data format: {'tax_type':{'tax_value':'tax_amount'}}"),
        ),
    ]
