# Generated by Django 3.1.4 on 2021-05-06 09:11

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20210504_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_data',
            field=models.JSONField(blank=True, default=orders.models.tax_data_default, help_text="Data format: {'tax_type':{'tax_value':'tax_amount'}}"),
        ),
    ]
