# Generated by Django 3.1.4 on 2021-07-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20210709_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_of_dd_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='dd_attachment',
            field=models.ImageField(blank=True, null=True, upload_to='direct_deposit_attachments'),
        ),
    ]
