# Generated by Django 3.1.4 on 2021-07-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210708_1658'),
        ('orders', '0030_auto_20210722_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variants'),
        ),
    ]
