# Generated by Django 3.1.4 on 2021-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20210904_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('direct deposit', 'Direct Deposit'), ('cash on pickup', 'Cash On Pickup')], default='paypal', max_length=100),
        ),
    ]
