# Generated by Django 3.1.4 on 2020-12-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_compare_compareitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, default='default/default-user.png', upload_to='store/products/%Y/%m/%d'),
        ),
    ]
