# Generated by Django 3.1.4 on 2020-12-31 19:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210101_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_specification',
            field=ckeditor.fields.RichTextField(blank=True, default='Test desc'),
        ),
    ]
