# Generated by Django 3.1.4 on 2021-04-28 11:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210304_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_specification',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
