# Generated by Django 3.1.4 on 2021-05-29 12:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210513_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
