# Generated by Django 3.1.4 on 2021-08-25 20:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='variant_data',
            field=models.JSONField(blank=True, default=products.models.variant_data_default, help_text="Data format: {'product_name':{'variant_type':'variant_value'}}"),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color'), ('Custom', 'Custom')], default='None', max_length=10),
        ),
    ]
