# Generated by Django 3.1.4 on 2021-08-26 18:45

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_attributevalue_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='variant_data',
            field=models.JSONField(blank=True, default=products.models.variant_data_default, help_text='Data should be in JSON format: {"attribute_name": "attribute_value", "attribute_name": "attribute_value"}'),
        ),
    ]
