# Generated by Django 3.1.4 on 2021-08-27 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210827_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='product_attribute',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.productattribute'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
