# Generated by Django 3.1.4 on 2021-09-05 13:15

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_dashboardimage'),
        ('products', '0024_auto_20210828_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPopupSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=9)),
                ('interval', models.CharField(choices=[('Seconds', 'Seconds'), ('Minutes', 'Minutes'), ('Hours', 'Hours')], default='Seconds', max_length=50)),
                ('background_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('text_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('notification_position', models.CharField(choices=[('Left Bottom Corner', 'Left Bottom Corner'), ('Right Bottom Corner', 'Right Bottom Corner'), ('Left Top Corner', 'Left Top Corner'), ('Right Top Corner', 'Right Top Corner')], default='Left Bottom Corner', max_length=50)),
                ('notification_style', models.CharField(choices=[('Rounded', 'Rounded'), ('Rectangled', 'Rectangled')], default='Rounded', max_length=50)),
                ('show_notification_after', models.CharField(max_length=9)),
                ('show_notification_after_seconds_minute', models.CharField(choices=[('Seconds', 'Seconds'), ('Minutes', 'Minutes'), ('Hours', 'Hours')], default='Seconds', max_length=50)),
                ('display_notification_for', models.CharField(max_length=9)),
                ('display_notification_for_seconds_minute', models.CharField(choices=[('Seconds', 'Seconds'), ('Minutes', 'Minutes'), ('Hours', 'Hours')], default='Seconds', max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.business')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
