# Generated by Django 3.1.4 on 2021-09-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_salespopup_salespopupsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespopupsetting',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='salespopupsetting',
            name='time',
        ),
        migrations.AddField(
            model_name='salespopup',
            name='interval',
            field=models.CharField(choices=[('Seconds', 'Seconds'), ('Minutes', 'Minutes'), ('Hours', 'Hours')], default='Seconds', max_length=50),
        ),
        migrations.AddField(
            model_name='salespopup',
            name='time',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
    ]
