# Generated by Django 3.1.4 on 2021-09-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210905_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespopupsetting',
            name='display_notification_for',
        ),
        migrations.RemoveField(
            model_name='salespopupsetting',
            name='display_notification_for_seconds_minute',
        ),
        migrations.RemoveField(
            model_name='salespopupsetting',
            name='show_notification_after',
        ),
        migrations.RemoveField(
            model_name='salespopupsetting',
            name='show_notification_after_seconds_minute',
        ),
    ]
