# Generated by Django 3.1.4 on 2021-09-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_testimonial_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
