# Generated by Django 3.1.4 on 2021-09-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210926_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
